export const ROUTES = {
  splash: '/splash',
  onboarding: '/onboarding',
  login: '/login',
  register: '/register',
  otp: '/otp',
  forgotPassword: '/forgot-password',
  roleSelection: '/role-selection',

  consumer: {
    home: '/consumer',
    usage: '/consumer/usage',
    bills: '/consumer/bills',
    payments: '/consumer/payments',
    alerts: '/consumer/alerts',
    profile: '/consumer/profile',
  },

  admin: {
    home: '/admin',
    consumers: '/admin/consumers',
    consumerNew: '/admin/consumers/new',
    meters: '/admin/meters',
    meter: (id) => `/admin/meters/${encodeURIComponent(id)}`,
    meterHealth: (id) => `/admin/meters/${encodeURIComponent(id)}/health`,
    meterControls: (id) => `/admin/meters/${encodeURIComponent(id)}/controls`,
    monitoring: '/admin/monitoring',
    billing: '/admin/billing',
    tariffs: '/admin/billing/tariffs',
    invoices: '/admin/billing/invoices',
    revenue: '/admin/billing/revenue',
    communication: '/admin/communication',
    commAnalytics: '/admin/communication/analytics',
    commLogs: '/admin/communication/logs',
    operations: '/admin/operations',
    faults: '/admin/faults',
    tamper: '/admin/tamper',
    incidents: '/admin/incidents',
    analytics: '/admin/analytics',
    sustainability: '/admin/analytics/sustainability',
    forecasting: '/admin/analytics/forecasting',
    alerts: '/admin/alerts',
    settings: '/admin/settings',
    security: '/admin/settings/security',
    more: '/admin/more',
    users: '/admin/users',
    audit: '/admin/audit',
    systemHealth: '/admin/system-health',
  },

  technician: {
    home: '/technician',
    workOrders: '/technician/work-orders',
    workOrder: (id) => `/technician/work-orders/${encodeURIComponent(id)}`,
    maintenance: '/technician/maintenance',
    profile: '/technician/profile',
  },

  billingOfficer: {
    home: '/billing-officer',
    tariffs: '/billing-officer/tariffs',
    invoices: '/billing-officer/invoices',
    revenue: '/billing-officer/revenue',
    profile: '/billing-officer/profile',
  },

  manager: {
    home: '/manager',
    analytics: '/manager/analytics',
    operations: '/manager/operations',
    communication: '/manager/communication',
    profile: '/manager/profile',
  },
};
